
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 180
	python
  fixme:
    enabled: false
    config:
      strings:
      - FIXME
      - BUG
ratings:
   paths:
   - "**.js"
   - "**.py"
