
engines:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
        python:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: false
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
  radon:
    enabled: true
    
ratings:
   paths:
   - "**.js"
   - "**.py"
