
engines:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
        python:
  fixme:
    enabled: false
    config:
      strings:
      - FIXME
      - BUG
ratings:
   paths:
   - "**.js"
   - "**.py"
